#include "Datasets_Menu.h"
#include <opencv2/opencv.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/core/core.hpp>
#include "package_bgs\DPZivkovicAGMM.h"
#include "ForegroundPostProcessing.h"

using namespace cv;

Mat fgMask, BM; //fg mask generated by MOG2 method

void main(){

	//Record source selection
	Datasets_Menu DM;	
	DM.Select_Dataset();

	//Load initial frame
	Mat Fr_o, Fr;
	DM.Get_Frame(Fr_o);
	resize(Fr_o, Fr, Size(480, 320));

	//Background subtraction 
	IBGS *bgs;
	bgs = new DPZivkovicAGMM;	

	//Foreground Postprocessing object
	ForegroundPostProcessing FP(Fr);

	//Time vars
	double t1, t2;

	for (;;){
		DM.Get_Frame(Fr_o);		

		if (Fr_o.empty())
			break;
		t1 = (double)cvGetTickCount();
		resize(Fr_o, Fr, Size(480, 320));
		bgs->process(Fr, fgMask, BM);
		t2 = (double)cvGetTickCount();
		printf("\nBGS time: %gms", (t2 - t1) / (cvGetTickFrequency()*1000.));

		//imshow("Gaussian Mixture Model (Zivkovic)", fgMask);		

		t1 = (double)cvGetTickCount();
		FP.postProcessingMain(fgMask);
		t2 = (double)cvGetTickCount();
		printf("\nPostprocess time: %gms", (t2 - t1) / (cvGetTickFrequency()*1000.));

		imshow("Frame", Fr);
		waitKey(1);
	}
	delete bgs;
}