#include "Datasets_Menu.h"
#include <opencv2/opencv.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/core/core.hpp>
#include "package_bgs\DPZivkovicAGMM.h"
#include "ForegroundPostProcessing.h"

using namespace cv;

Mat fgMask, BM; //fg mask generated by MOG2 method

void main(){

	//Record source selection
	Datasets_Menu DM;	
	DM.Select_Dataset();

	//Load initial frame
	Mat Fr_o, Fr;
	DM.Get_Frame(Fr_o);
	resize(Fr_o, Fr, Size(480, 320));

	//Background subtraction 
	IBGS *bgs;
	bgs = new DPZivkovicAGMM;	

	//Foreground Postprocessing object
	ForegroundPostProcessing FP(Fr);

	for (;;){
		DM.Get_Frame(Fr_o);		

		if (Fr_o.empty())
			break;

		resize(Fr_o, Fr, Size(480, 320));
		bgs->process(Fr, fgMask, BM);
		imshow("Gaussian Mixture Model (Zivkovic)", fgMask);		

		FP.postProcessingMain(fgMask);

		imshow("Frame", Fr);
		waitKey(1);
	}
	delete bgs;
}