#include "Datasets_Menu.h"
#include <opencv2/opencv.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/video/background_segm.hpp>
#include "package_bgs\DPZivkovicAGMM.h"

using namespace cv;

Mat fgMask, BM; //fg mask generated by MOG2 method

void main(){
	Datasets_Menu DM;
	
	DM.Select_Dataset();

	//Load initial frame
	Mat Fr_o, Fr;
	DM.Get_Frame(Fr_o);
	resize(Fr_o, Fr, Size(480, 320));

	IBGS *bgs;
	bgs = new DPZivkovicAGMM;

	for (;;){
		DM.Get_Frame(Fr_o);		

		if (Fr_o.empty())
			break;

		resize(Fr_o, Fr, Size(480, 320));
		bgs->process(Fr, fgMask, BM);

		imshow("Frame", Fr);
		waitKey(1);
	}
	delete bgs;
}